[package]
name = "muli-queue"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
muli-core = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
chrono = { workspace = true }
