[package]
name = "muli-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["time"] }
argon2 = { workspace = true }
url = { workspace = true }
http = "1"
base64 = { workspace = true }
tracing = { workspace = true }
aes-gcm = "0.10"
rand = "0.8"
